import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <Link href="/app-a">
            <a className={styles.card}>
              <h2>App A</h2>
            </a>
          </Link>

          <Link href="/app-b">
            <a className={styles.card}>
              <h2>App B</h2>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
